### ISSUE TITLE
Support for 3 phase charger

### ISSUE THREAD

**Issue by amgstone** [krasnoukhov/homeassistant-oncharger#12]
Hello, can you add support for 3 phase charger? Now does not show consumption by phases.
https://oncharger.com.ua/ua/p1044770084-zaryadnaya-stantsiya-dlya.html

**Comment by krasnoukhov** [comment]
I don't own such a device so it would be hard for me to verify. Do you want to take a stab at it and submit a PR?

**Comment by amgstone** [comment]
what does PR mean?

**Comment by krasnoukhov** [comment]
Pull Request (here on Github)

**Comment by amgstone** [comment]
I will have 3 phases in 2 weeks and we can start testing. You can open a Pull Request.

**Comment by amgstone** [comment]
And you can connect to my computer and pull all the data you need and add it to the code

**Comment by krasnoukhov** [comment]
No, you submit it to Github and I have access to it right here

**Comment by amgstone** [comment]
ok, tell the sequence of actions how and what information to give Van.

**Comment by krasnoukhov** [comment]
Do you have experience with Python? If not, I guess it might be too hard for you to add support for the device
