### ISSUE TITLE
How boost mode works

### ISSUE THREAD

**Issue by amgstone** [krasnoukhov/homeassistant-oncharger#14]
Please tell me which sensor should I insert so that boost mode starts working? Current sensor that goes to the house, before charging the car?
![boost](https://github.com/krasnoukhov/homeassistant-oncharger/assets/63303107/cb934ee2-b87d-43c0-88f4-34de5bc414ed)

**Comment by krasnoukhov** [comment]
Hello, there's a helpful message below the input that should clarify things. Yes, you're thinking correct
